### ISSUE TITLE
Merge Underwear.css into Uniform.css repo

### ISSUE THREAD

**Issue by warpech** [Starcounter/underwear.css#76]
Merge Underwear into Uniform repo, including:

- move Underwear's `index.html` demo page into `index.html` in Uniform
- move the build process
- move the issues (I can do it)

**Comment by warpech** [comment]
This issue skips an important question. Should Underwear.css + Uniform.css be merged into a single stylesheet?

Pros:

+ we now allow using of Uniform classes in light DOM
+ we sometimes need Underwear styles in shadow DOM

Cons: 

?

cc @tomalec, @alshakero

**Comment by alshakero** [comment]
- There are cases when you don't want underwear, as in can't have it, but need uniform. For instance when do you don't want Normalizer stuff. And vice-versa; there are cases where you want only underwear and can't have uniform.

- I'm a big fan of freedom in general. The more freedom the better. Two seperate files mean more freedom but less advantage too, that's why I suggest three automatically generated files in `dist`: `underwear.css`, [`commando.css`](https://www.google.pl/search?ei=56kjW63qJKXM6ASgn5vgBA&q=go+commando&oq=go+commando&gs_l=psy-ab.3..0l10.2344.5467.0.5814.12.10.0.2.2.0.93.770.10.10.0....0...1c.1.64.psy-ab..0.12.778...33i160k1j0i67k1j0i10k1.0.sMjY9UaGipQ) (uniform without underwear) and `uniform.css` (full uniform).

- Larger file sizes, this is considerable in CSS since it's always fetched unless `preloaded`.

**Comment by warpech** [comment]
I like the idea of having three files in dist.

The name `commando.css` is *nuts*! :D

**Comment by tomalec** [comment]
I think we should keep separate source files, for our own mental model. It may increase the cognitive load for maintenance, but let's see how it will go, it's still cheaper than two reports.

The use cases for using Uni without Under, are fading away for me a little, but I can still see use cases for using just `underwear.css` in my custom element definition without a need for `uni`.

The name `commando.css` rocks! Even if we don't have any use case for it we should keep it just for this name.

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/uniform.css/pull/131
